import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Tony's Tech Automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-red-100 text- to-blue-100 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="border-b-2 border-blue-500 via-red-500 text-blue-500 py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-bold font-Lato text-1xl">II  Sir Anthony  +254726 138 288</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-blue-500 text- to-red-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-3xl font-bold font-Lato py-2 text-blue-500  dark:text-teal-400 md:text-2xl">
              Tony's Tech Automation
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              ""
            </h3>
            <p className="text-md font-Lato py-5 leading-8 text-gray-800 dark:text-gray-200  ">
              Are you looking for a professional logo for your business, company or organization? Look no further. We specialize in creating stunning 3D Logos and letterheads that will help your brand stand out. Our services don't stop there. We also also design business cards, posters and more. We also offer Computer Online services like Business Registration, Company Registration, AGPO Application, Motor vehicle transfer & Ownership acceptance, Kenyan Passport Application, Temporary Passport Application, New Number Plates Application, TSC Number Application and any other online service.
            </p>
            
            <div className="mx-auto bg-gradient-to-b from-blue-500 via-red-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image alt="description" src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl font-bold font-Lato py-1 dark:text-white">Services I Offer</h3>
            <p className="text-md py-2 font-Lato leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a Computer Tech Expert, I've  done remote work for
              <span className="text-teal-500"> Businesses, Companies </span>
              and collaborated with talanted people to create digital products and Clean Services.
            <p className="text-md font-Lato py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              and Online Services.
            </p>
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image alt="description" src={design} width={120} height={80} />
              <h3 className="font-bold font-Lato text-lg font-medium pt-8 pb-2  ">
                Logo Designs
              </h3>
              <p className="py-2 font-Lato">
                Creating elegant Logo designs suited for your needs following core
                design theory.
              </p>
              <h4 className="font-Lato py-4 text-teal-600">Logos' I make Include</h4>
              <p className="font-Lato text-gray-800 py-1">3D Logos</p>
              <p className="font-Lato text-gray-800 py-1">Letter Heads</p>
              <p className="font-Lato text-gray-800 py-1">Business Cards</p>
              <p className="font-Lato text-gray-800 py-1">Posters & Banners</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image alt="description" src={code} width={180} height={80} />
              <h3 className="font-bold font-Lato text-lg font-medium pt-8 pb-2 ">
                BRS - Business Registration Services
              </h3>
              <p className="font-Lato py-2">
                Do you have an idea for your next great Business or Company? Let's make it a
                reality, through Registration.
              </p>
              <h4 className="font-Lato py-4 text-teal-600">Services Include</h4>
              <p className="font-Lato text-gray-800 py-1">Company Regstration</p>
              <p className="font-Lato text-gray-800 py-1">Business Registration</p>
              <p className="font-Lato text-gray-800 py-1">AGPO Application</p>
              <p className="font-Lato text-gray-800 py-1">CR12 Renewal</p>
              
            </div>
            <div className="font-Lato text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image alt="description" src={consulting} width={170} height={80} />
              <h3 className="font-bold text-lg font-medium pt-8 pb-2 ">NTSA & KRA Services</h3>
              <p className="font-Lato py-2">
                Are you in need of assistance of NTSA and KRA Services, Look no more , Beause we Gatch YOU!!
              </p>
              <h4 className="font-Lato py-4 text-teal-600">Services include</h4>
              <p className="font-Lato text-gray-800tupy-1">LogbooktuTranser & Acceptance</p>
              <p className="font-Lato text-gray-800 py-1">Motor  Vehicle Inspection Booking</p>
              <p className="font-Lato text-gray-800 py-1">New Reflective Plates Application</p>
              <p className="font-Lato text-gray-800 py-1">Smart DL Application</p>
              <p className="font-Lato text-gray-800 py-1">Road Service Licence Application</p>
              <p className="font-Lato text-gray-800 py-1">PSV Application</p>
              <p className="font-Lato text-gray-800 py-1">TSV Application</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="font-bold font-Lato text-3xl py-1 dark:text-white ">Portfolio</h3>
            <p className=" font-Lato text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Below are some of Client's work which i've done lately and have served them satisfation
              
            </p>
            <p className="font-Lato text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, Feel free to inquire. Friendly Price.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/6 flex-1 ">
              <Image alt="description"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/6 flex-1">
              <Image alt="description"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/6 flex-1">
              <Image alt="description"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/6 flex-1">
              <Image alt="description"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/6 flex-1">
              <Image alt="description"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
          
            
            </div>
          </div>
        </section>
      </main>
      <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
    </div>
    
  );
}
